name: Build and Push ThingsBoard Edge Docker Image

on:
  push:
    branches:
      - master
      # or specify other branches/tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # 3) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Log in to Docker Hub (or any other registry)
      - name: Log in to Docker
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            --username "${{ secrets.DOCKERHUB_USERNAME }}" \
            --password-stdin

      # 5) Run build.sh, which uses Maven to build projects and (optionally) push images.
      #    If you want to push images from within the script, make sure the relevant
      #    Maven profile or arguments are enabled (see notes below).
      - name: Build (and possibly push) Docker images
        run: |
          chmod +x build.sh
          # Example: if you want to pass a project to build:
          # ./build.sh "msa/web-ui"
          #
          # If you want to push multi-arch images from within Maven,
          # uncomment or add the appropriate arguments in build.sh.
          # For example:
          #   MAVEN_OPTS="-Xmx1024m" NODE_OPTIONS="--max_old_space_size=4096" \
          #   mvn -T2 clean install -DskipTests -Dpush-docker-image=true -Ddockerfile.skip=false
          #
          # Otherwise, just run the default script:
          ./build.sh
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          # You can set additional environment variables here, if needed.

      # (Optional) 6) If you prefer to push Docker images *outside* of the Maven script
      # after building them, you can do so via Docker Buildx as well, for example:
      #
      - name: Build and push multi-arch image via docker/build-push-action
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: >-
            ishikht/tb-edge:latest
            ishikht/tb-edge:${{ github.sha }}
